// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeVqVW7VqPh4psNIXRkLx7MDq2g2SH4DU',
    appId: '1:349168949080:web:f8ae351089d30253b3f72d',
    messagingSenderId: '349168949080',
    projectId: 'stockwatcher-79394',
    authDomain: 'stockwatcher-79394.firebaseapp.com',
    storageBucket: 'stockwatcher-79394.firebasestorage.app',
    measurementId: 'G-Q7WTMKSXYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH99fyK9SGkBs7jwpU5MvJsvUb0VxsgZw',
    appId: '1:349168949080:android:23bbae06c9e967bab3f72d',
    messagingSenderId: '349168949080',
    projectId: 'stockwatcher-79394',
    storageBucket: 'stockwatcher-79394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBauQL2lhQiXRSJGVW7xb7ag79GV84OaQo',
    appId: '1:349168949080:ios:30d2233835986d2fb3f72d',
    messagingSenderId: '349168949080',
    projectId: 'stockwatcher-79394',
    storageBucket: 'stockwatcher-79394.firebasestorage.app',
    iosBundleId: 'com.example.stockwatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBauQL2lhQiXRSJGVW7xb7ag79GV84OaQo',
    appId: '1:349168949080:ios:30d2233835986d2fb3f72d',
    messagingSenderId: '349168949080',
    projectId: 'stockwatcher-79394',
    storageBucket: 'stockwatcher-79394.firebasestorage.app',
    iosBundleId: 'com.example.stockwatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeVqVW7VqPh4psNIXRkLx7MDq2g2SH4DU',
    appId: '1:349168949080:web:308ad17779bc6c9eb3f72d',
    messagingSenderId: '349168949080',
    projectId: 'stockwatcher-79394',
    authDomain: 'stockwatcher-79394.firebaseapp.com',
    storageBucket: 'stockwatcher-79394.firebasestorage.app',
    measurementId: 'G-QN07B4X4Z5',
  );
}
